function formatCurrency(value) {
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value || 0);
}

function formatNumber(value) {
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(value || 0);
}

export default function ForecastPanel({ report }) {
  const preview = report.forecast.slice(0, 5);
  const averageForecast = report.forecast.length
    ? report.forecast.reduce((total, row) => total + row.forecast, 0) / report.forecast.length
    : 0;

  return (
    <article className="panel panel--forecast">
      <div className="section-heading">
        <div>
          <p className="section-heading__eyebrow">REVENUE FORECAST</p>
          <h2>Next 30 days</h2>
        </div>
        <span className="section-heading__action">{report.selected_model}</span>
      </div>
      <div className="forecast-summary">
        <div>
          <span className="muted-label">Forecast window</span>
          <strong>{report.forecast_start}</strong>
          <span>to {report.forecast_end}</span>
        </div>
        <div>
          <span className="muted-label">Average daily revenue</span>
          <strong>{formatCurrency(averageForecast)}</strong>
        </div>
      </div>
      <div className="forecast-table" role="table" aria-label="Revenue forecast preview">
        <div className="forecast-table__row forecast-table__row--head" role="row">
          <span>Date</span><span>Forecast</span>
        </div>
        {preview.map((row) => (
          <div className="forecast-table__row" key={row.date} role="row">
            <span>{row.date}</span><strong>{formatCurrency(row.forecast)}</strong>
          </div>
        ))}
      </div>
      <p className="report-note">Values are read from the selected-model forecast generated by the backend.</p>
    </article>
  );
}

export function ModelComparisonPanel({ report }) {
  return (
    <article className="panel panel--comparison">
      <div className="section-heading">
        <div>
          <p className="section-heading__eyebrow">MODEL COMPARISON</p>
          <h2>Validation scoreboard</h2>
        </div>
        <span className="section-heading__action">Actual holdout</span>
      </div>
      <div className="comparison-table" role="table" aria-label="Revenue model comparison">
        <div className="comparison-table__row comparison-table__row--head" role="row">
          <span>Model</span><span>MAE</span><span>RMSE</span>
        </div>
        {report.model_comparison.map((row) => (
          <div className={`comparison-table__row ${row.selected ? "comparison-table__row--selected" : ""}`} key={row.model} role="row">
            <span>{row.model}{row.selected ? " · selected" : ""}</span>
            <span>{formatNumber(row.mae)}</span>
            <strong>{formatNumber(row.rmse)}</strong>
          </div>
        ))}
      </div>
      <p className="report-note">Lower validation RMSE selected <strong>{report.selected_model}</strong> for revenue.</p>
    </article>
  );
}
