"""add sale source file lineage

Revision ID: 7cffe796e522
Revises: 6436c67d5128
Create Date: 2026-10-08 20:02:49.464752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cffe796e522'
down_revision: Union[str, Sequence[str], None] = '6436c67d5128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "sales",
        sa.Column(
            "source_file",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE sales
        SET source_file = CASE
            WHEN source_system = 'UCI'
                 AND source_row_id < 525461
                THEN 'online_retail_v1.csv'
            WHEN source_system = 'UCI'
                 AND source_row_id >= 525461
                THEN 'online_retail_v2.csv'
            ELSE 'unknown'
        END
        """
    )

    op.alter_column(
        "sales",
        "source_file",
        existing_type=sa.String(length=255),
        nullable=False,
    )

    op.create_index(
        op.f("ix_sales_source_file"),
        "sales",
        ["source_file"],
        unique=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_source_file'), table_name='sales')
    op.drop_column('sales', 'source_file')
    # ### end Alembic commands ###
