"""add sales source lineage

Revision ID: 825ffda3874f
Revises: 44d88a1dbe45
Create Date: 2026-10-08 14:32:58.548452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825ffda3874f'
down_revision: Union[str, Sequence[str], None] = '44d88a1dbe45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('source_system', sa.String(length=50), nullable=False))
    op.add_column('sales', sa.Column('source_row_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sales_source_system'), 'sales', ['source_system'], unique=False)
    op.create_unique_constraint('uq_sales_source_system_row', 'sales', ['source_system', 'source_row_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sales_source_system_row', 'sales', type_='unique')
    op.drop_index(op.f('ix_sales_source_system'), table_name='sales')
    op.drop_column('sales', 'source_row_id')
    op.drop_column('sales', 'source_system')
    # ### end Alembic commands ###
