"""extend invoice persistence fields

Revision ID: 8c8e55faf178
Revises: 825ffda3874f
Create Date: 2026-10-08 15:38:22.267561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8e55faf178'
down_revision: Union[str, Sequence[str], None] = '825ffda3874f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=150), nullable=False))
    op.add_column('invoices', sa.Column('product_name', sa.String(length=200), nullable=False))
    op.add_column('invoices', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('created_by', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'created_by')
    op.drop_column('invoices', 'unit_price')
    op.drop_column('invoices', 'quantity')
    op.drop_column('invoices', 'product_name')
    op.drop_column('invoices', 'customer_name')
    # ### end Alembic commands ###
